// Code generated by FlashORM. DO NOT EDIT.
const { Queries: PostQueries } = require('./post');
const { Queries: UsersQueries } = require('./users');

// Combine all query classes into one
class Queries {
  constructor(db) {
    this.db = db;
    const _post = new PostQueries(db);
    Object.getOwnPropertyNames(Object.getPrototypeOf(_post)).forEach(name => {
      if (name !== 'constructor' && typeof _post[name] === 'function') {
        this[name] = _post[name].bind(_post);
      }
    });

    const _users = new UsersQueries(db);
    Object.getOwnPropertyNames(Object.getPrototypeOf(_users)).forEach(name => {
      if (name !== 'constructor' && typeof _users[name] === 'function') {
        this[name] = _users[name].bind(_users);
      }
    });
  }
}

/**
 * Create a new database client
 * @param {Object} db - Database connection (pg.Pool, postgres instance, mysql2.Pool, better-sqlite3 instance, or bun:sqlite instance)
 * @returns {Queries}
 */
function New(db) {
  return new Queries(db);
}

module.exports = { New, Queries };
