// Code generated by FlashORM. DO NOT EDIT.

export interface Users {
  id: number;
  name: string;
  address: string | null;
  isadmin: boolean;
  email: string;
  created_at: Date;
  updated_at: Date;
  role: 'admin' | 'moderator' | 'user' | 'guest';
}

export interface Categories {
  id: number;
  name: string;
  created_at: Date;
}

export interface Posts {
  id: number;
  user_id: number;
  category_id: number;
  title: string;
  content: string;
  created_at: Date;
  updated_at: Date;
  status: 'draft' | 'published' | 'archived';
}

export interface Comments {
  id: number;
  post_id: number;
  user_id: number;
  content: string;
  created_at: Date;
}

export interface GetComplexUserAnalyticsResult {
  id: number;
  name: string;
  email: string;
  role: 'admin' | 'moderator' | 'user' | 'guest';
  isadmin: boolean;
  user_created_at: string;
  total_posts: string;
  published_posts: string;
  draft_posts: string;
  total_comments: string;
  posts_commented_on: string;
  categories_used: string;
  category_names: string;
  last_post_date: string;
  last_comment_date: string;
  avg_post_length: number;
  activity_level: string;
  engagement_score: string;
}

export interface GetPostWithCommentsResult {
  post_id: number;
  title: string;
  content: string;
  author: string;
  comment_text: string;
  commenter: string;
}

export interface GetPostDetailsWithAllRelationsResult {
  id: number;
  title: string;
  content: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  updated_at: Date;
  author_id: string;
  author_name: string;
  author_email: string;
  author_role: string;
  author_is_admin: string;
  category_id: number;
  category_name: string;
  comment_count: number;
  unique_commenters: number;
  all_comments: string | null;
  commenter_names: string[] | null;
  last_comment_date: Date | null;
  content_length: number | null;
  hours_since_created: number | null;
}

export class Queries {
  constructor(db: any);

  createCategory(name: string): Promise<Categories | null>;
  createUser(name: string, email: string, address: string, isadmin: boolean): Promise<number>;
  getUserByEmail(email: string): Promise<Users | null>;
  createPost(user_id: number, category_id: number, title: string, content: string): Promise<Posts | null>;
  createComment(post_id: number, user_id: number, content: string): Promise<Comments | null>;
  getPostWithComments(id: number): Promise<GetPostWithCommentsResult[]>;
  getPostDetailsWithAllRelations(id: number): Promise<GetPostDetailsWithAllRelationsResult | null>;
  getComplexUserAnalytics(total_posts: number, total_comments: number, limit: number): Promise<GetComplexUserAnalyticsResult[]>;
}

export function New(db: any): Queries;
