// Code generated by FlashORM. DO NOT EDIT.

class Queries {
  constructor(db) {
    this.db = db;
    this._stmts = new Map();
  }

  async createCategory(name) {
    let stmt = this._stmts.get('createCategory');
    if (!stmt) {
      stmt = `INSERT INTO categories (name) VALUES ($1) RETURNING *;`;
      this._stmts.set('createCategory', stmt);
    }
    const r = await this.db.query(stmt, [name]);
    return r.rows[0] || null;
  }

}

module.exports = { Queries };
