# Code generated by FlashORM. DO NOT EDIT.

from typing import Any
from .post import Queries as PostQueries
from .other import Queries as OtherQueries
from .users import Queries as UsersQueries

# Combine all query classes into one
class Queries:
    """Unified query interface that delegates to individual query modules."""
    
    def __init__(self, db):
        self.db = db
        self._post = PostQueries(db)
        self._other = OtherQueries(db)
        self._users = UsersQueries(db)

    def __getattr__(self, name):
        """Delegate attribute access to query modules."""
        if hasattr(self._post, name):
            return getattr(self._post, name)
        elif hasattr(self._other, name):
            return getattr(self._other, name)
        elif hasattr(self._users, name):
            return getattr(self._users, name)
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

def new(db: Any) -> Queries:
    """
    Create a new database client.
    
    Args:
        db: Database connection (asyncpg.Pool, psycopg3 Connection, aiomysql.Pool, PyMySQL connection, aiosqlite connection, or sqlite3 connection)
    
    Returns:
        Queries: An instance of the Queries class
    """
    return Queries(db)
