# Code generated by FlashORM. DO NOT EDIT.

from typing import Optional, List, Any, Literal
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

@dataclass
class GetuserRow:
    id: int
    name: str
    email: str
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at']
        )

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def get_user(self, id: int) -> Optional[GetuserRow]:
        _key = 'get_user'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, name, email, created_at FROM users WHERE id = $1 LIMIT 1;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, id)
        return GetuserRow._make_fast(result[0]) if result else None

