# Code generated by FlashORM. DO NOT EDIT.

from typing import Optional, List, Any, Literal
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

@dataclass
class CreateuserRow:
    id: int
    name: str
    email: str
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at']
        )

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def create_user(self, name: str, email: str) -> Optional[CreateuserRow]:
        _key = 'create_user'
        if _key not in self._stmts:
            self._stmts[_key] = """INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email, created_at;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, name, email)
        return CreateuserRow._make_fast(result[0]) if result else None

