# Code generated by FlashORM. DO NOT EDIT.

from typing import Optional, List, Any, Literal
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

@dataclass
class ListusersRow:
    id: int
    name: str
    email: str
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at']
        )

@dataclass
class UpdateuserRow:
    id: int
    name: str
    email: str
    created_at: datetime

    @classmethod
    def _make_fast(cls, record):
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at']
        )

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def list_users(self) -> List[ListusersRow]:
        _key = 'list_users'
        if _key not in self._stmts:
            self._stmts[_key] = """SELECT id, name, email, created_at FROM users ORDER BY created_at DESC;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt)
        return [ListusersRow._make_fast(row) for row in result]

    async def update_user(self, id: int, name: str, email: str) -> Optional[UpdateuserRow]:
        _key = 'update_user'
        if _key not in self._stmts:
            self._stmts[_key] = """UPDATE users SET name = $2, email = $3 WHERE id = $1 RETURNING id, name, email, created_at;"""
        stmt = self._stmts[_key]
        result = await self.db.fetch(stmt, id, name, email)
        return UpdateuserRow._make_fast(result[0]) if result else None

    async def delete_user(self, id: int) -> int:
        _key = 'delete_user'
        if _key not in self._stmts:
            self._stmts[_key] = """DELETE FROM users WHERE id = $1;"""
        stmt = self._stmts[_key]
        await self.db.execute(stmt, id)
        return 1

