-- Migration: init
-- Created: 2026-05-27T01:04:37Z

-- +migrate Up
-- Create tables in dependency order (referenced tables first)
CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "posts" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" SERIAL PRIMARY KEY,
  "post_id" INT NOT NULL REFERENCES "posts"("id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "likes" (
  "id" INT PRIMARY KEY,
  "post_id" INT NOT NULL REFERENCES "posts"("id") ON DELETE CASCADE,
  "comment_id" INT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "shares" (
  "id" INT PRIMARY KEY,
  "post_id" INT NOT NULL REFERENCES "posts"("id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "hshsh" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Clean up legacy objects if they exist
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "fuck_s" CASCADE;
DROP TABLE IF EXISTS "fuck_table" CASCADE;
DROP TABLE IF EXISTS "test_s" CASCADE;
DROP TABLE IF EXISTS "vddsvsd" CASCADE;
DROP TABLE IF EXISTS "_graft_migrations" CASCADE;
DROP TYPE IF EXISTS "AccountStatus" CASCADE;
DROP TYPE IF EXISTS "Gender" CASCADE;
DROP TYPE IF EXISTS "NotificationStatus" CASCADE;
DROP TYPE IF EXISTS "RankedPostType" CASCADE;
DROP TYPE IF EXISTS "Role" CASCADE;
DROP TYPE IF EXISTS "SignupSource" CASCADE;
DROP TYPE IF EXISTS "fuck_mode" CASCADE;
DROP TYPE IF EXISTS "fuck_role" CASCADE;
DROP TYPE IF EXISTS "ChatStatus" CASCADE;
DROP TYPE IF EXISTS "MoodType" CASCADE;
DROP TYPE IF EXISTS "role" CASCADE;
DROP TYPE IF EXISTS "test_em" CASCADE;
DROP TYPE IF EXISTS "AccountType" CASCADE;
DROP TYPE IF EXISTS "ActionStatus" CASCADE;
DROP TYPE IF EXISTS "NotificationType" CASCADE;
DROP TYPE IF EXISTS "mode_fuck" CASCADE;
DROP TYPE IF EXISTS "ActionType" CASCADE;
DROP TYPE IF EXISTS "ChatContentStatus" CASCADE;
DROP TYPE IF EXISTS "Platforms" CASCADE;

-- +migrate Down
DROP TABLE IF EXISTS "hshsh" CASCADE;
DROP TABLE IF EXISTS "shares" CASCADE;
DROP TABLE IF EXISTS "likes" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "posts" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
